# Generated by Django 3.2 on 2024-07-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id_falla', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('operario', models.CharField(max_length=255)),
                ('parcela_sector', models.CharField(max_length=255)),
                ('falla', models.TextField()),
                ('posible_causa', models.TextField()),
                ('posible_solucion', models.TextField()),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_conclusion', models.DateTimeField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('operario_conclusion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
