# Generated by Django 3.2 on 2025-03-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelascsv',
            fields=[
                ('parcela', models.AutoField(primary_key=True, serialize=False)),
                ('responsable', models.CharField(max_length=255)),
                ('sponsor', models.CharField(max_length=255)),
                ('descripcion_parcela', models.CharField(db_column='Descripcion Parcela', max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('auditores', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'parcelascsv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaporacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('operario', models.CharField(max_length=255, verbose_name='Operario')),
                ('totalizador_condensado', models.FloatField(default=None, null=True, verbose_name='Totalizador condensado (m3)')),
                ('OT_BO2101', models.FloatField(default=None, null=True, verbose_name='OT BO2101 (%)')),
                ('presion_salida_IC2102', models.FloatField(default=None, null=True, verbose_name='Presión de salida del IC2102')),
                ('presion_BO2101', models.FloatField(default=None, null=True, verbose_name='Presion BO2101')),
                ('presion_ingreso_IC2101', models.FloatField(default=None, null=True, verbose_name='Presion Ingreso IC2101')),
                ('presion_egreso_IC2101_ingreso_IC2103', models.FloatField(default=None, null=True, verbose_name='Presion Egreso IC2101/Ingreso IC2103')),
                ('presion_egreso_IC2103', models.FloatField(default=None, null=True, verbose_name='Presion Egreso IC2103')),
                ('temp_ingreso_agua_IC701', models.FloatField(default=None, null=True, verbose_name='Temp Ingreso Agua IC701 (°C)')),
                ('temp_salida_agua_IC701', models.FloatField(default=None, null=True, verbose_name='Temp Salida Agua IC701 (°C)')),
                ('presion_ingreso_agua_IC701', models.FloatField(default=None, null=True, verbose_name='Presión Ingreso Agua IC701 (bar)')),
                ('presion_salida_agua_IC701', models.FloatField(default=None, null=True, verbose_name='Presión Salida Agua IC701 (bar)')),
                ('presion_salida_vahos_IC701', models.FloatField(default=None, null=True, verbose_name='Presión Salida Vahos IC701 (bar)')),
                ('observaciones', models.TextField(default=None, null=True, verbose_name='Observaciones')),
            ],
        ),
    ]
