# Generated by Django 3.2 on 2025-03-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaporacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaporacion',
            options={'ordering': ['-operario', '-fecha'], 'verbose_name': 'Evaporacion', 'verbose_name_plural': 'Evaporaciones'},
        ),
        migrations.AlterField(
            model_name='evaporacion',
            name='OT_BO2101',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='OT BO2101 (%)'),
        ),
        migrations.AlterField(
            model_name='evaporacion',
            name='observaciones',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='evaporacion',
            name='presion_BO2101',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Presion BO2101'),
        ),
        migrations.AlterField(
            model_name='evaporacion',
            name='presion_egreso_IC2101_ingreso_IC2103',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Presion Egreso IC2101/Ingreso IC2103'),
        ),
        migrations.AlterField(
            model_name='evaporacion',
            name='presion_egreso_IC2103',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Presion Egreso IC2103'),
        ),
        migrations.AlterField(
            model_name='evaporacion',
            name='presion_ingreso_IC2101',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Presion Ingreso IC2101'),
        ),
        migrations.AlterField(
            model_name='evaporacion',
            name='presion_ingreso_agua_IC701',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Presión Ingreso Agua IC701 (bar)'),
        ),
        migrations.AlterField(
            model_name='evaporacion',
            name='presion_salida_IC2102',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Presión de salida del IC2102'),
        ),
        migrations.AlterField(
            model_name='evaporacion',
            name='presion_salida_agua_IC701',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Presión Salida Agua IC701 (bar)'),
        ),
        migrations.AlterField(
            model_name='evaporacion',
            name='presion_salida_vahos_IC701',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Presión Salida Vahos IC701 (bar)'),
        ),
        migrations.AlterField(
            model_name='evaporacion',
            name='temp_ingreso_agua_IC701',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Temp Ingreso Agua IC701 (°C)'),
        ),
        migrations.AlterField(
            model_name='evaporacion',
            name='temp_salida_agua_IC701',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Temp Salida Agua IC701 (°C)'),
        ),
        migrations.AlterField(
            model_name='evaporacion',
            name='totalizador_condensado',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Totalizador condensado (m3)'),
        ),
        migrations.AlterModelTable(
            name='evaporacion',
            table='evaporacion',
        ),
    ]
