# Generated by Django 3.2 on 2024-07-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaporacion', '0002_falla'),
    ]

    operations = [
        migrations.AddField(
            model_name='falla',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='falla',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fallas/'),
        ),
    ]
