# Generated by Django 3.2 on 2025-03-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaporacion', '0002_auto_20250322_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaporacion',
            name='presion_ingreso_agua_IC701',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Presion Ingreso Agua IC701 (bar)'),
        ),
        migrations.AlterField(
            model_name='evaporacion',
            name='presion_salida_IC2102',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Presión Egreso IC2102'),
        ),
    ]
