# Generated by Django 3.2 on 2025-03-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaporacion', '0003_auto_20240711_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelascsv',
            fields=[
                ('parcela', models.AutoField(primary_key=True, serialize=False)),
                ('responsable', models.CharField(max_length=255)),
                ('sponsor', models.CharField(max_length=255)),
                ('descripcion_parcela', models.CharField(db_column='Descripcion Parcela', max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('auditores', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'parcelascsv',
                'managed': False,
            },
        ),
    ]
