# Generated by Django 3.2 on 2025-03-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaporacion', '0003_auto_20250322_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaporacion',
            name='presion_salida_agua_IC701',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Presion Salida Agua IC701 (bar)'),
        ),
        migrations.AlterField(
            model_name='evaporacion',
            name='presion_salida_vahos_IC701',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Presion Salida Vahos IC701 (bar)'),
        ),
    ]
