# Generated by Django 3.2 on 2025-03-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaporacion', '0004_parcelascsv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Falla',
        ),
    ]
