# Generated by Django 3.2 on 2025-03-20 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaporacion', '0005_delete_falla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaporacion',
            name='OT_EYECTOR_1',
        ),
        migrations.RemoveField(
            model_name='evaporacion',
            name='OT_EYECTOR_2',
        ),
        migrations.RemoveField(
            model_name='evaporacion',
            name='OT_vva_traspaso_ef1_a_ef3',
        ),
        migrations.RemoveField(
            model_name='evaporacion',
            name='PT01_PT02',
        ),
        migrations.RemoveField(
            model_name='evaporacion',
            name='PT03',
        ),
        migrations.RemoveField(
            model_name='evaporacion',
            name='PT04',
        ),
        migrations.RemoveField(
            model_name='evaporacion',
            name='PT05',
        ),
        migrations.RemoveField(
            model_name='evaporacion',
            name='ST_EFECTO_2_SALIDA',
        ),
        migrations.RemoveField(
            model_name='evaporacion',
            name='caudal_vl',
        ),
        migrations.RemoveField(
            model_name='evaporacion',
            name='densidad',
        ),
        migrations.RemoveField(
            model_name='evaporacion',
            name='densidad_LAB',
        ),
        migrations.RemoveField(
            model_name='evaporacion',
            name='filetes_FERM',
        ),
        migrations.RemoveField(
            model_name='evaporacion',
            name='nivel_tk_condensado',
        ),
        migrations.RemoveField(
            model_name='evaporacion',
            name='potencia_sepevap',
        ),
        migrations.RemoveField(
            model_name='evaporacion',
            name='temperatura',
        ),
        migrations.RemoveField(
            model_name='evaporacion',
            name='viscosidad',
        ),
    ]
